In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [6]:
myarray = np.array(mylist)

In [7]:
myarray

array([1, 2, 3])

In [8]:
type(myarray)

numpy.ndarray

In [9]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((5))

array([1., 1., 1., 1., 1.])

In [23]:
len(np.linspace(0,5,21))

21

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.random.rand(5,2)

array([[0.23567201, 0.68883096],
       [0.130027  , 0.20403109],
       [0.50926933, 0.29742156],
       [0.10857349, 0.73028293],
       [0.95181768, 0.24016911]])

In [31]:
np.random.randn(10)

array([-1.15155877, -2.11086887,  0.20239821, -0.38545511, -1.76504179,
        1.58580224, -1.45333399, -0.4788597 , -1.69276405, -0.22418401])

In [32]:
np.random.randn(2,3)

array([[-0.14048626,  2.08001414, -0.1936256 ],
       [ 0.52884773,  0.60582916, -0.91668781]])

In [35]:
np.random.randint(0,101,10)

array([58, 99, 27, 72,  4, 97, 23, 81, 10, 51])

In [36]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [37]:
arr = np.arange(0,25)

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
ranarr = np.random.randint(0,101,10)

In [41]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [43]:
ranarr.max()

99

In [44]:
ranarr.min()

2

In [45]:
ranarr.argmax()

5

In [46]:
ranarr.argmin()

7

In [47]:
ranarr.dtype

dtype('int64')

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
arr.shape

(25,)

In [50]:
arr = arr.reshape(5,5)

In [51]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
arr.shape

(5, 5)

In [55]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])